### PR TITLE
v0.1.1

### PR DESCRIPTION
**Pull request by donavanbecker**
- add github actions for a new release

### CODE REVIEW

**Comment by donavanbecker** [comment]
@NorthernMan54 any chance you can help us with getting these GitHub actions to work correctly 😉

**Comment by NorthernMan54** [comment]
@donavanbecker Let me dig into them, may be a few days though

**Comment by donavanbecker** [comment]
accidents published this.... so we will have to publish v0.1.1

**Comment by donavanbecker** [comment]
See #11

**Pull request closed without merging**
