### PR TITLE
Wait for link requests

### PR DESCRIPTION
**Pull request by dnicolson**
## :recycle: Current situation

Opening a plugin's settings in Homebridge UI can result in jank due to the large CSS file loading.

## :bulb: Proposed solution

Wait for the CSS file to load.

Before:

https://github.com/homebridge/plugin-ui-utils/assets/2276355/f3da06f8-65e5-4b38-bb09-9e033a49d236

After:

https://github.com/homebridge/plugin-ui-utils/assets/2276355/c292eeb9-ebca-4fb7-a93e-a0eeba5d9051

### CODE REVIEW

**Review by bwp91 — APPROVED** [review]

**Comment by bwp91** [comment]
Fab, thanks!

**Comment by donavanbecker** [comment]
@dnicolson, this is homebridge-switchbot@2.8.0-beta.19, can you verify it is working for you?

**Comment by dnicolson** [comment]
@donavanbecker the `plugin-ui-utils` code comes from this path in my instance:
`/opt/homebridge/lib/node_modules/homebridge-config-ui-x/public/assets/plugin-ui-utils/ui.js`

This code doesn't appear to be run:
`/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/@homebridge/plugin-ui-utils/dist/ui.js`

**Comment by bwp91** [comment]
this PR is still needed right? was this a dependency for https://github.com/homebridge/homebridge-config-ui-x/pull/1522?

**Comment by donavanbecker** [comment]
@dnicolson New test version of Homebridge UI is out.

Thanks!

**Comment by dnicolson** [comment]
@bwp91 these are two distinct issues but the goal is the same.

Can someone also create a new release and bump https://github.com/homebridge/homebridge-config-ui-x/blob/abd12e3/ui/package.json#L23?

**Comment by donavanbecker** [comment]
@dnicolson Will do, any more PRs need on Config UI? If not I will create a release and release it.

**Comment by dnicolson** [comment]
That should be it, thanks.

**Pull request merged**
